version: '3'

services:
  bot:
    build: .
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs
    networks:
      - countr-db
    labels:
      io.portainer.accesscontrol.teams: "promise-solutions"

networks:
  countr-db:
    name: countr-premium-access-manager
    external: true
