version: '3'

services:
  bot:
    build: .
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs
    networks:
      - countr-db

networks:
  countr-db:
    name: countr-premium-access-manager
    external: true
