name: Docker Compose
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
  workflow_dispatch:

jobs:
  build:
    name: Test Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3

    - name: Copy docker test environment
      run: cp ".docker/docker-test.env" ".env"

    - name: Test docker compose build
      run: docker compose build