name: Docker Compose
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
  workflow_dispatch:

jobs:
  build:
    name: Test Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # v3

    - name: Copy docker test environment
      run: cp ".docker/docker-test.env" ".env"

    - name: Test docker compose build
      run: docker compose build