name: Linting
on:
  push:
    branches:
    - djs-14
  pull_request:
    branches:
    - djs-14

jobs:
  eslint:
    name: ESLint
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3

    - name: Set up node
      uses: actions/setup-node@f1f314fca9dfce2769ece7d933488f076716723e # tag=v1
      with:
        node-version: "16.x"

    - name: Set up module cache
      uses: actions/cache@937d24475381cd9c75ae6db12cb4e79714b926ed # tag=v2
      id: cache-packages
      with:
        path: node_modules
        key: ${{ hashFiles('**/package-lock.json') }}

    - name: Install dependencies
      run: npm ci
      if: steps.cache-packages.outputs.cache-hit != 'true'

    - name: Run ESLint
      run: npm run lint